name: Android Debug Build & Share

on:
  push:
    tags:
      - 'v*'   # Runs only when you push a tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4. Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5. Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 6. Build Debug APK
      - name: Build Release aar
        run: ./gradlew bundleReleaseAar

      # 7. Upload APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # 8. Upload AAR as artifact
      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aar
          path: docscan/build/outputs/aar/docscan-release.aar

      # 9. Send Email with Artifact Link
#      - name: Send Email with APK Link
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.gmail.com
#          server_port: 465
#          username: ${{ secrets.EMAIL_USERNAME }}
#          password: ${{ secrets.EMAIL_PASSWORD }}
#          subject: "New Android Debug Build Available"
#          to: tester1@example.com,tester2@example.com
#          from: "UrbanFT <${{ secrets.EMAIL_USERNAME }}>"
#          body: |
#            Hi Testers,
#
#            A new debug build is available.
#
#            👉 Download it here:
#            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
#
#            Thanks,
#            Urban FT